name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted     
#     runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2./ru
      with:
        python-version: 3.9
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome    
      run: |
        sudo apt install google-chrome-stable
 
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run Automation Tests
      run: python main.py -v
#       run: pipenv run python main.py test functional_tests.tests.test_selenium.test_exams -v 2

    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: Logs/*.*

    - name: List current directory
      run: |
        ls -a
        cd Logs
        echo
        echo "Files in \"Logs\" folder"
        ls
        echo
        echo "Content of \"automation.log\" file "
        cat automation.log
      
      
